# Generated by Django 5.2.6 on 2025-09-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                ("popularity", models.IntegerField()),
                ("tempo", models.FloatField(null=True)),
                ("valence", models.FloatField(null=True)),
                ("speechiness", models.FloatField(null=True)),
                ("danceability", models.FloatField(null=True)),
                ("liveness", models.FloatField(null=True)),
                ("velocity", models.FloatField(null=True)),
                ("mean_popularity", models.FloatField(null=True)),
                ("median_popularity", models.FloatField(null=True)),
                ("std_popularity", models.FloatField(null=True)),
                ("retrieval_frequency", models.IntegerField(null=True)),
                (
                    "trend",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("stable", "Stable")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
