# Generated by Django 5.2.6 on 2025-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="genres",
            field=models.TextField(blank=True, null=True),
        ),
    ]
