# Generated by Django 5.2.6 on 2025-09-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "spotify_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("genres", models.CharField(blank=True, default="", max_length=1024)),
                (
                    "artist_popularity",
                    models.IntegerField(
                        null=True, verbose_name="Popularidade do Artista"
                    ),
                ),
                (
                    "num_hits",
                    models.IntegerField(null=True, verbose_name="Número de Hits"),
                ),
                (
                    "num_collab_hits",
                    models.IntegerField(null=True, verbose_name="Hits em Colaboração"),
                ),
                (
                    "betweenness_centrality",
                    models.FloatField(
                        null=True, verbose_name="Centralidade de Intermediação"
                    ),
                ),
                (
                    "degree_centrality",
                    models.FloatField(null=True, verbose_name="Centralidade de Grau"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HitSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("album", models.CharField(blank=True, default="", max_length=255)),
                (
                    "popularity",
                    models.IntegerField(verbose_name="Popularidade da Faixa"),
                ),
                ("release_date", models.DateField(null=True)),
                ("explicit", models.BooleanField(default=False)),
                (
                    "is_collaboration",
                    models.BooleanField(default=False, verbose_name="É Colaboração"),
                ),
                (
                    "market_of_origin",
                    models.CharField(
                        default="BR - Brasil",
                        max_length=100,
                        verbose_name="Mercado-alvo da Análise",
                    ),
                ),
                ("danceability", models.FloatField(null=True)),
                ("energy", models.FloatField(null=True)),
                ("valence", models.FloatField(null=True)),
                ("tempo", models.FloatField(null=True)),
                ("liveness", models.FloatField(null=True)),
                ("acousticness", models.FloatField(null=True)),
                ("speechiness", models.FloatField(null=True)),
                ("instrumentalness", models.FloatField(null=True)),
                (
                    "genre_heterogeneity_index",
                    models.FloatField(
                        null=True, verbose_name="Índice de Heterogeneidade de Gênero"
                    ),
                ),
                (
                    "avg_artist_betweenness",
                    models.FloatField(
                        null=True, verbose_name="Média da Intermediação dos Artistas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("velocity", models.FloatField(null=True)),
                ("mean_popularity", models.FloatField(null=True)),
                ("std_popularity", models.FloatField(null=True)),
                ("trend", models.CharField(default="stable", max_length=10)),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="hit_songs", to="ars_network.artist"
                    ),
                ),
            ],
        ),
    ]
